#if !canImport(ObjectiveC)
import XCTest

extension StringLocalizationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringLocalizationTests = [
        ("testCount", testCount),
        ("testCountSelection", testCountSelection),
        ("testLocalized", testLocalized),
        ("testMissing", testMissing),
        ("testParameters", testParameters),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(StringLocalizationTests.__allTests__StringLocalizationTests),
    ]
}
#endif
